mbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  shoulder_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  forearm_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: forearm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  hand_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: hand_joint
    pid: {p: 1.0, i: 0.00, d: 0.0}
